# Generated by Django 4.1.6 on 2023-02-09 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='pic_url',
            field=models.TextField(null=True),
        ),
    ]
