# Generated by Django 4.1.6 on 2023-02-09 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_location_pic_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='pic_url',
            new_name='picture_url',
        ),
    ]
