# Base it on the python:3 base image
# Run Python in unbuffered mode
# Set the work directory to the normal /app directory
# Copy the requirements.txt into the image
# Install the Python requirements from requirements.txt
# For the default command to run, it should run the intended Python file that you will create: CMD python attendees/account_info_consumer.py
FROM python:3
ENV PYTHONUNBUFFERED 1
WORKDIR /app
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

## ALTER THIS LINE TO ADD CRONTABS AND START SERVICE
CMD python attendees/account_info_consumer.py
